CREATE TABLE `building_subject` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `district_id` bigint(20) DEFAULT NULL,
  `street_id` bigint(20) DEFAULT NULL,
  `block_id` bigint(20) DEFAULT NULL,
  `owner_unit_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fire_manager` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_phone` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sup_charge_unit_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `industry_supervision_depart` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `use_time` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '��λ�����£�',
  `base_building_class` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '�ο��ֵ�building_class',
  `con_cover_area` double DEFAULT NULL COMMENT '��λ��ƽ����',
  `con_build_area` double DEFAULT NULL COMMENT '��λ��ƽ����',
  `con_build_hight` int(11) DEFAULT NULL,
  `con_floors` int(11) DEFAULT NULL,
  `con_under_floors` int(11) DEFAULT NULL,
  `con_class` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '�ο��ֵ�building_con_class',
  `surface_function` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '�ο��ֵ�surface_function',
  `underground_function` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '�ο��ֵ�underground_function',
  `use_unit_num` int(11) DEFAULT NULL,
  `base_code` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thumb_img` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remark` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mod_date` datetime DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL COMMENT '��ȡ��ǰ��̨��¼�û�',
  `maintenance_unit` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `third_party_fire_detection` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `design_unit` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `construct_unit` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `total_area` double DEFAULT NULL,
  `overground_area` double DEFAULT NULL,
  `underground_area` double DEFAULT NULL,
  `base_building_category` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


